name = "Vanilla Reimagined"
author = "BX Team"
version = "26.2-2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc2b8f04fde2554714e6a51213bad34037e48435a118a553774683b1d35346fe"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
